services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_II
    ports:
      - "3000:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Estiam2026*
<<<<<<< HEAD
    restart: always
=======
    restart: always
>>>>>>> b4a9ee16b8175a0f48ff42a1fff6e3e559ee8807
